export const LOCATIONS = {
    LOAD: 'LOCATIONS_LOAD',
    LOAD_SUCCESS: 'LOCATIONS_LOAD_SUCCESS',
    LOAD_FAIL: 'LOCATIONS_LOAD_FAILURE',
    CLICK: 'LOCATION_CLICK'
}

export const TREASURE = {
    CHECK: 'TREASURE_CHECK',
    FOUND: 'TREASURE_FOUND',
    NOT_FOUND: 'TREASURE_NOT_FOUND',
    CHECK_FAILURE: 'TREASURE_CHECK_FAILURE'
}

export default { LOCATIONS, TREASURE };